{
    "name": "Ordomatics Platform",
    "version": "18.0.1.0.3",
    "category": "Technical",
    "summary": "Platform-level dependencies for all Ordomatics deployments",
    "license": "LGPL-3",
    "depends": [
        # Core
        "base",
        "web",
        "contacts",
        "product",
        "account",
        "mail",
        # OCA
        "queue_job",
        "fastapi",
        "endpoint_route_handler",
        # LLM suite
        "llm",
        "llm_store",
        "llm_tool",
        "llm_generate",
        "llm_transcribe",
        "llm_transcribe_job",
        "llm_assistant",
        "llm_mcp_server",
        "llm_mcp_client",
        "llm_ollama",
        "llm_anthropic",
        "llm_nomic",
        "llm_skills",
        # Storage (S3 filestore)
        "fs_attachment_s3",
        # WhatsApp
        "whatsapp_base",
        "whatsapp_messaging",
        "whatsapp_voip",
        "whatsapp_template",
        "whatsapp_llm",
        "whatsapp_catalog",
        "whatsapp_billing",
        # Billing
        "payment_wave",
        "billing_llm",
        "payment_llm",
        "product_llm",
    ],
    "installable": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
}
